# Generated by Django 5.2.4 on 2025-07-09 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bridge_auth',
            fields=[
                ('bridge_auth_id', models.AutoField(primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
