# Generated by Django 5.2.4 on 2025-07-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_bridge_auth_bridgeauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgeauth',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
