# Generated by Django 5.2.4 on 2025-07-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bridgeauth_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridgeauth',
            name='access_token',
            field=models.TextField(),
        ),
    ]
