#!/bin/bash

# Define the path to the virtual environment and Django project directory
VENV_PATH="/working/venv"
PROJECT_DIR="/working"
REQUIREMENTS_PATH="/working/requirements.txt"
export PYTHONUNBUFFERED=1

if [ $1 == "django" ]; then
    echo "ENTRYPOINT: using django entrypoint"
    if [ ! -d "$VENV_PATH" ]; then
        echo "Virtual environment not found. Creating one..."
        python3 -m venv "$VENV_PATH"
    fi
    source "${VENV_PATH}/bin/activate"
    if [ -f "$REQUIREMENTS_PATH" ]; then
        echo "Installing requirements from ${REQUIREMENTS_PATH}..."
        pip install -r "$REQUIREMENTS_PATH"
    else
        echo "Requirements file not found at ${REQUIREMENTS_PATH}. Skipping pip install."
    fi

    python3 "${PROJECT_DIR}/manage.py" collectstatic --noinput
    python3 "${PROJECT_DIR}/manage.py" runserver 0.0.0.0:5000
else
    echo "ENTRYPOINT: invalid entrypoint specifier"
fi
